version = "1.0"

[metadata]
author_name = ""PortexAI""

[metadata.portex]
task_id = ""7jn6aI""
bundle = "simple_bundle"

[verifier]
timeout_sec = 900

[verifier.env]
OPENROUTER_API_KEY = "${OPENROUTER_API_KEY}"

[agent]
timeout_sec = 900

[environment]
build_timeout_sec = 600
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0